"""Second migration

Revision ID: d72741a0ee75
Revises: 0f4cffd6134e
Create Date: 2024-08-07 14:47:58.696174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72741a0ee75'
down_revision: Union[str, None] = '0f4cffd6134e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('primary_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_categories_primary_id'), 'categories', ['primary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_primary_id'), table_name='categories')
    op.drop_column('categories', 'primary_id')
    # ### end Alembic commands ###
